name: de-lambda-deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        type: string
        default: dev
        required: false

jobs:
  run-tests:
    if: false # this will cause the job to be skipped - delete to enable 
    name: run-tests
    runs-on: ubuntu-latest
    steps:
    - name: run-checks
      run: make run-checks

  # deploy-lambda:
  #   if: false # this will cause the job to be skipped - delete to enable 
  #   name: deploy-lambda
  #   steps:
  #   - name: run-checks
  #     run: make run-checks
    