name: de-lambda-deployment

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    name: run-tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Set Up Python
      uses: actions/setup-python@v5
      with: 
        python-version: '3.12'
    - name: Install Make
      run: sudo apt install make -y
    - name: Run Tests
      run: make all

  # deploy-lambda:
  #   name: deploy-lambda
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: run-checks
  #     run: make run-checks